### PR TITLE
feat: use different latency metrics for HTTP and HTTPS latency tests

### PR DESCRIPTION
**Pull request by Hill-98**
The downside is that we can't get the URL of the tests configured by Clash

### CODE REVIEW

**Comment by kunish** [comment]
How did you come up with these two arbitrary latency values? Any evidence?

**Comment by Hill-98** [comment]
I based this on latency testing under HTTP and HTTPS for the proxies I use.

They are not 100% consistent, but can be used as a reference.

**Comment by kunish** [comment]
It's already a bad user experience when the latency is as high as 1000ms which is fullon one second.

As a user you will notice the latency indicator should not be green at all.

**Comment by kunish** [comment]
As for `we can't get the URL of the tests configured by Clash`, it's a known issue since we cant get it from any of the endpoints core provided

**Comment by Hill-98** [comment]
But it's HTTPS latency, HTTPS latency is what it is.

Because a complete HTTPS needs to transmit multiple data packets, unlike HTTP, it only transmits one data packet.

My proxy has a latency of 170ms for HTTP and 700ms for HTTPS.

**Comment by kunish** [comment]
Maybe shrink these values down a little bit, say 500ms and 800ms, what do you think?

**Comment by Hill-98** [comment]
Of course, according to the existing test results. (Based on tests I already have proxies for)

It would be more appropriate to change the two values ​​to 800 and 1500 respectively.

**Comment by kunish** [comment]
Cool, lets ship it and see any feedbacks

**Pull request merged**
